### ISSUE TITLE
build:web  babel报错

### ISSUE THREAD

**Issue by tiajinsha** [umbrella22/electron-react-template#4]
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/tianjinsha/Documents/electron-react-template-master/src/renderer/view/app/App.tsx: Missing initializer in const declaration. (9:9)

   7 | import TitleBar from "@/components/common/TitleBar"
   8 |
>  9 | const App: FC = () => {
     |          ^
  10 |   return (
  11 |     <div className="App">
  12 |       <div className="App-header">
    at instantiate (/Users/tianjinsha/Documents/electron-react-template-master/node_modules/@babel/parser/lib/index.js:72:32)

**Comment by umbrella22** [comment]
已解决
